name: red_ela
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  top_snackbar_flutter: ^3.1.0
  flutter_secure_storage: ^9.0.0
  uuid: ^4.4.0
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.2
  firebase_storage: ^11.7.1
  cloud_firestore: ^4.16.1
  provider: ^6.1.2
  googleapis: ^13.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  connectivity_plus: ^6.0.2
  google_sign_in: ^6.2.1
  http: ^1.2.1
  multiple_result: ^5.1.0
  accordion: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/nodos.png
