name: red_ela
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  top_snackbar_flutter: ^3.1.0
  uuid: ^4.4.0
  firebase_core: ^3.1.0
  firebase_core_web: ^2.17.2
  firebase_crashlytics: ^4.0.1
  firebase_auth: ^5.1.0
  firebase_auth_web: ^5.12.2
  firebase_storage: ^12.0.1
  firebase_app_check: ^0.3.0+1
  cloud_firestore: ^5.0.1
  cloud_firestore_web: ^4.0.1
  provider: ^6.1.2
  googleapis: ^13.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  connectivity_plus: ^6.0.2
  google_sign_in: ^6.2.1
  http: ^1.2.1
  multiple_result: ^5.1.0
  accordion: ^2.6.0
  flutter_otp_text_field: ^1.1.3+2
  phone_form_field: ^9.2.3
  url_launcher: ^6.2.6
  go_router: ^14.1.0
  app_links: ^6.0.1
  phone_numbers_parser: ^8.2.1
  encrypt: ^5.0.3
  flutter_dotenv: ^5.1.0
  flutter_email_sender: ^6.0.3
  border_bottom_navigation_bar: ^0.0.4
  syncfusion_flutter_calendar: ^26.1.35
  dropdown_search: ^5.0.6
  mailer: ^6.1.0
  responsive_framework: ^1.4.0
  firebase_messaging: ^15.0.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/redela_logo.png
    - assets/images/redela_logo.png
    - assets/dotenv
