name: red_ela
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  top_snackbar_flutter: ^3.1.0
  flutter_secure_storage: ^9.0.0
  uuid: ^4.4.0
  firebase_core: ^2.31.0
  firebase_crashlytics: 3.5.5
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.1
  cloud_firestore: ^4.16.1
  provider: ^6.1.2
  googleapis: ^13.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  connectivity_plus: ^6.0.2
  google_sign_in: ^6.2.1
  http: ^1.2.1
  multiple_result: ^5.1.0
  accordion: ^2.6.0
  flutter_otp_text_field: ^1.1.3+2
  phone_form_field: ^9.2.3
  url_launcher: ^6.2.6
  go_router: ^14.1.0
  app_links: ^6.0.1
  phone_numbers_parser: ^8.2.1
  encrypt: ^5.0.3
  flutter_dotenv: ^5.1.0
  flutter_email_sender: ^6.0.3
  border_bottom_navigation_bar: ^0.0.4
  syncfusion_flutter_calendar: ^25.2.6+1
  dropdown_search: ^5.0.6
  mailer: ^6.1.0
  awesome_notifications_core: ^0.9.3
  awesome_notifications: any
  awesome_notifications_fcm: any
  onesignal_flutter: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/redela_logo.png
    - assets/images/redela_logo.png
    - /env/.env
